### ISSUE TITLE
Add compatibility with Medicines No More Limited

### ISSUE THREAD

**Issue by BioHazardN7** [SilvDev/Incapped_Weapons_Patch#1]
In [Medicines No More Limited v1.2.3](https://forums.alliedmods.net/showthread.php?t=336226) you can raise your HP level above 100 using first aid kits or pills (adrenaline). But if you hurt and temporary health is 250 (for example), using pills (adrenaline) with the recovery function enabled, the character will have 250 permanent health. In another similar plugin (Incapped Pills Pop v4.2) this works fine.

**Comment by SilvDev** [comment]
I think the fix needs to come from the Medicines No More Limited plugin.
